Vorname: {{ $data['first_name'] }}
Nachname: {{ $data['last_name'] }}
Email: {{ $data['email'] }}
Situation: {{ $data['situation'] }}
Anrede: {{ $data['salutation'] }}
Fon: {{ $data['phone'] }}
Strasse: {{ $data['street'] }}
PLZ: {{ $data['zip'] }}
Ort: {{ $data['city'] }}
